name: jdsd

on:
  schedule:
    - cron: '0 7 * * *'

  workflow_dispatch:

jobs:
  jdsd:
    runs-on: ubuntu-latest

    steps:
      - name: Check out this repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install packages
        run: pip3 install -r requirements.txt

      - name: Run the script
        env:
          KEY: ${{ secrets.KEY }}
          TOKEN: ${{ secrets.TOKEN }}
          SKEY: ${{ secrets.SKEY }}
          BURL: ${{ secrets.BURL }}
        run: python fuck_jdsd.py
